"""empty message

Revision ID: fefa02fb142e
Revises: 
Create Date: 2024-04-14 19:29:43.516232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fefa02fb142e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('g_auth_verify', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('schedule',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('Monday', sa.String(length=200), nullable=True),
    sa.Column('Tuesday', sa.String(length=200), nullable=True),
    sa.Column('Wednesday', sa.String(length=200), nullable=True),
    sa.Column('Thursday', sa.String(length=200), nullable=True),
    sa.Column('Friday', sa.String(length=200), nullable=True),
    sa.Column('Saturday', sa.String(length=200), nullable=True),
    sa.Column('Sunday', sa.String(length=200), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    op.drop_table('user')
    # ### end Alembic commands ###
